# Generated by Django 6.0.5 on 2026-05-28 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa kategorii')),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategorie',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(max_length=50, unique=True, verbose_name='Numer inwentarzowy')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa sprzętu')),
                ('status', models.CharField(choices=[('available', 'Dostępny'), ('repair', 'W naprawie'), ('written_off', 'Spisany')], default='available', max_length=20, verbose_name='Status')),
                ('added_date', models.DateField(auto_now_add=True, verbose_name='Data dodania')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.category', verbose_name='Kategoria')),
            ],
            options={
                'verbose_name': 'Sprzęt',
                'verbose_name_plural': 'Sprzęt',
            },
        ),
    ]
